### ISSUE TITLE
`make` command works with root permissions only

### ISSUE THREAD

**Issue by rabajaj0509** [kpcyrd/i-probably-didnt-backdoor-this#3]
Can someone look into the issue? I am using Fedora 33 and had  created a Unix group called docker and add users to it, so ideally it should not ask say permission denied.

```.bash
$ make
docker run --rm -v "/home/vagrant/i-probably-didnt-backdoor-this:/app" -w /app -u "1000:1000" \
	rust@sha256:8463cc29a3187a10fc8bf5200619aadf78091b997b0c3941345332a931c40a64 \
	cargo build --release --locked --target=x86_64-unknown-linux-musl
error: Permission denied (os error 13) at path "/app/targetzF01pS"
make: *** [Makefile:2: build] Error 101

```

**Comment by rabajaj0509** [comment]
I might be completely wrong here. Just thought of reporting this anyway :+1:

**Comment by kpcyrd** [comment]
hi!

it seems the docker part of it is working fine, could you check if your `/home/vagrant/i-probably-didnt-backdoor-this` folder is writable by uid 1000? `/app/targetzF01pS` sounds weird but I'm assuming this is cargo trying to create the `/app/target/` folder and failing due to permission problems on `/app/`.
